# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd5642d28c86730dafc76a29ba59ed1f2c2e8d6e84b8258c8eff1d14bfc163fab134bb8cf300869e565be27ccb4f46a2d996a729b27bae2f089a6b5d2afbaef8
  stripe_publishable_key: pk_test_plrMsklylDSMK0Cxv3OqpTFB
  stripe_secret_key: sk_test_SOgXv7fQPmfobUFL9TmNPPrY
  twilio_sid: <%= ENV["ACfb965aa5afab6d586529c4d7bdc64533"] %>
  twilio_token: <%= ENV["76587f8e40d9a6efccf700ece69a8e79"] %>   
test:
  secret_key_base: 92b9db4868dba98e6e361c4c176244fd95a37b19e113e3f75fb97d671a7c5ae740d45a1438a99221bcbe012b833a08bd572fa3aef5821cd8f3e19cd6f39d7a21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
